### ISSUE TITLE
参考#331 #334  未解决【多LoRA权重合并 时报size mismatch】

### ISSUE THREAD

**Issue by liuxiaohao-xn** [ymcui/Chinese-LLaMA-Alpaca#431]
###  多LoRA权重合并 时报 mismatch错误
我参考过  #331 #334 并未找到解决办法，请求解答，万分感谢。

下面是我的训练步骤：
1. 下载原生的llama-7B权重，用convert_llama_weights_to_hf.py转换成llama-7B-hf权重；
2. 下载chinese-llama-plus-lora-7b权重，与llama-7B-hf用 merge_llama_with_chinese_lora.py合并得到chinese-llama-7B-plus-hf权重；
3. 然后用run_clm_sft_with_peft.py基于chinese-llama-7B-plus-hf训练得到lora权重adapter_model.bin

用下面步骤得到adapter_model.bin，参考#361
```bash
mkdir lora_model
cp pytorch_model.bin lora_model/adapter_model.bin
cp Chinese-LLaMA-LoRA-7b/adapter_config.json lora_model/
cp Chinese-LLaMA-LoRA-7b/*token* lora_model/
```
4. 然后用merge_llama_with_chinese_lora.py将llama-7B-hf权重， chinese-llama-plus-lora-7b权重， adapter_model.bin权重合并得到最终的chinese-alpaca-7B-Plus权重模型

**但是执行步骤4时候报错了**

### 报错日志

```bash
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: /asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: /asr_lu/user/luchuanze/cudnn11/lib: did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 110
CUDA SETUP: Loading binary /asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda110.so...
Base model: /asr_lu/user/liuxiaohao/project/LLaMA/llama_hf/7B
LoRA model(s) ['/asr_lu/user/liuxiaohao/project/LLaMA/Chinese-LLaMA_lora/Chinese-LLaMA-Plus-7B', '/asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/output_dir/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000/lora_model']:
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:08<00:00,  4.20s/it]
Peft version: 0.3.0.dev0
Loading LoRA for 7B model
Loading LoRA /asr_lu/user/liuxiaohao/project/LLaMA/Chinese-LLaMA_lora/Chinese-LLaMA-Plus-7B
Extended vocabulary size to 49953
Merging with merge_and_unload...
Loading LoRA /asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/output_dir/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000/lora_model
Traceback (most recent call last):
  File "merge_llama_with_chinese_lora.py", line 248, in <module>
    lora_model = PeftModel.from_pretrained(
  File "/asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/peft/peft_model.py", line 163, in from_pretrained
    model = set_peft_model_state_dict(model, adapters_weights)
  File "/asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/peft/utils/save_and_load.py", line 74, in set_peft_model_state_dict
    model.load_state_dict(peft_model_state_dict, strict=False)
  File "/asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
        size mismatch for base_model.model.model.embed_tokens.weight: copying a param with shape torch.Size([49954, 4096]) from checkpoint, the shape in current model is torch.Size([49953, 4096]).
        size mismatch for base_model.model.lm_head.weight: copying a param with shape torch.Size([49954, 4096]) from checkpoint, the shape in current model is torch.Size([49953, 4096]).
```
### 报错源码
```python
for lora_index, lora_model_path in enumerate(lora_model_paths):
        print(f"Loading LoRA {lora_model_path}")
        tokenizer = LlamaTokenizer.from_pretrained(lora_model_path)
        if base_model.get_input_embeddings().weight.size(0) != len(tokenizer):
            base_model.resize_token_embeddings(len(tokenizer))
            print(f"Extended vocabulary size to {len(tokenizer)}")

        first_weight = base_model.model.layers[0].self_attn.q_proj.weight
        first_weight_old = first_weight.clone()

        if hasattr(peft.LoraModel,'merge_and_unload'):
            lora_model = PeftModel.from_pretrained(    # 这里报错
                base_model,
                lora_model_path,
                device_map={"": "cpu"},
                torch_dtype=torch.float16,
            )
```
在合并llama-7B-hf权重与chinese-llama-plus-lora-7b权重并没有报错；此时base_model.get_input_embeddings().weight.size(0) == len(tokenizer)==49953；

但在合并adapter_model.bin权重时报size mismatch。

下面是我的合并脚本
```bash
# llama_hf + llama_lora + alpaca_lora
# 7B-Plus
base_model=/asr_lu/user/liuxiaohao/project/LLaMA/llama_hf/7B
llama_lora_model=/asr_lu/user/liuxiaohao/project/LLaMA/Chinese-LLaMA_lora/Chinese-LLaMA-Plus-7B
alpaca_lora_model=/asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/output_dir/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000/lora_model
output_type=huggingface
output_dir=/asr_lu/user/liuxiaohao/project/LLaMA/chinese_alpaca_lora_merge_llama_hf/${output_type}/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000


python merge_llama_with_chinese_lora.py \
    --base_model ${base_model} \
    --lora_model ${llama_lora_model},${alpaca_lora_model} \
    --output_type ${output_type} \
    --output_dir ${output_dir}
```
### 必查项目（前三项只保留你要问的）

- [x] **基础模型**： Alpaca-Plus
- [x] **运行系统**： Linux 
- [x] **问题分类**： 模型转换和合并 
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案

**Comment by ymcui** [comment]
```
3. 然后用run_clm_sft_with_peft.py基于chinese-llama-7B-plus-hf训练得到lora权重adapter_model.bin
```

提供一下这一步的命令，重点是`--tokenizer_name_or_path`参数传进去的是什么文件（llama or alpaca）？

**Comment by kevinuserdd** [comment]
> ```
> 3. 然后用run_clm_sft_with_peft.py基于chinese-llama-7B-plus-hf训练得到lora权重adapter_model.bin
> ```
> 
> 提供一下这一步的命令，重点是`--tokenizer_name_or_path`参数传进去的是什么文件（llama or alpaca）？

同样的错，传进去的tokenizer文件就是词表新增合并后的

**Comment by airaria** [comment]
请提供以下信息：

1. `adapter_model.bin`中的embed_tokens.weight的大小是否为(49954,4096)？

2. `/asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/output_dir/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000/lora_model`这个路径，是你训练的Alpaca-LoRA路径吗？里面是否有`tokenizer.model`? 如果用LlamaTokenizer加载这个路径，得到的`len(tokenizer)`是多少？
```python
lora_model_path = "/asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/output_dir/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000/lora_model"
tokenizer = LlamaTokenizer.from_pretrained(lora_model_path)
print(len(tokenizer))
```

**Comment by airaria** [comment]
> mkdir lora_model
cp pytorch_model.bin lora_model/adapter_model.bin
cp Chinese-LLaMA-LoRA-7b/adapter_config.json lora_model/
cp Chinese-LLaMA-LoRA-7b/*token* lora_model/

应该是你这里的tokenizer用错了。你把llama的tokenizer copy到了lora_model（alpaca模型）下。
应该从Chinese-Alpaca-LoRA-7b中拷贝`*token*`到lora_model下。

**Comment by kevinuserdd** [comment]
> > mkdir lora_model
> > cp pytorch_model.bin lora_model/adapter_model.bin
> > cp Chinese-LLaMA-LoRA-7b/adapter_config.json lora_model/
> > cp Chinese-LLaMA-LoRA-7b/_token_ lora_model/
> 
> 应该是你这里的tokenizer用错了。你把llama的tokenizer copy到了lora_model（alpaca模型）下。 应该从Chinese-Alpaca-LoRA-7b中拷贝`*token*`到lora_model下。

不是啊，你自己用微调生成的lora合并过吗？ 是代码这个地方的问题：
    if tokenizer.pad_token is None:
        num_new_tokens = smart_tokenizer_and_embedding_resize(
            special_tokens_dict=dict(pad_token=DEFAULT_PAD_TOKEN),
            tokenizer=tokenizer,
            model=None,)
这里会导致新增一个token，变成49954个，导致在合并的时候会不匹配

**Comment by airaria** [comment]
> > > mkdir lora_model
> > > cp pytorch_model.bin lora_model/adapter_model.bin
> > > cp Chinese-LLaMA-LoRA-7b/adapter_config.json lora_model/
> > > cp Chinese-LLaMA-LoRA-7b/_token_ lora_model/
> > 
> > 
> > 应该是你这里的tokenizer用错了。你把llama的tokenizer copy到了lora_model（alpaca模型）下。 应该从Chinese-Alpaca-LoRA-7b中拷贝`*token*`到lora_model下。
> 
> 不是啊，你自己用微调生成的lora合并过吗？ 是代码这个地方的问题： if tokenizer.pad_token is None: num_new_tokens = smart_tokenizer_and_embedding_resize( special_tokens_dict=dict(pad_token=DEFAULT_PAD_TOKEN), tokenizer=tokenizer, model=None,) 这里会导致新增一个token，变成49954个，导致在合并的时候会不匹配

Alpaca的词表数量是49954，比LLaMA多一个，本身是这么设计的，没有问题。

**Comment by liuxiaohao-xn** [comment]
> > ```
> > 3. 然后用run_clm_sft_with_peft.py基于chinese-llama-7B-plus-hf训练得到lora权重adapter_model.bin
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 提供一下这一步的命令，重点是`--tokenizer_name_or_path`参数传进去的是什么文件（llama or alpaca）？
> 
> 同样的错，传进去的tokenizer文件就是词表新增合并后的


>


> ```
> 3. 然后用run_clm_sft_with_peft.py基于chinese-llama-7B-plus-hf训练得到lora权重adapter_model.bin
> ```
> 
> 提供一下这一步的命令，重点是`--tokenizer_name_or_path`参数传进去的是什么文件（llama or alpaca）？

感谢回复！
用的chinese-llama-7B-plus-hf，下面是我的训练脚本
```bash
lr=1e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05
pretrained_model=/asr_lu/user/liuxiaohao/project/LLaMA/chinese-llama_lora_merge_llama_hf/huggingface/7B-Plus
**这里就是chinese-llama-7B-plus-hf路径**
chinese_tokenizer_path=/asr_lu/user/liuxiaohao/project/LLaMA/chinese-llama_lora_merge_llama_hf/huggingface/7B-Plus  
dataset_dir=/asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/data_dir/train_2M_CN_rm_5000
per_device_train_batch_size=32
per_device_eval_batch_size=32
training_steps=100 # 改成epoch=4
gradient_accumulation_steps=1
output_dir=/asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/output_dir/7B-Plus_lora_train_2M_CN_rm_5000
peft_model=path/to/peft/model/dir
validation_file=/asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/eval_data_dir/test_5000.json

deepspeed_config_file=ds_zero2_no_offload.json

CUDA_VISIBLE_DEVICES=2,3 torchrun --nnodes 1 --nproc_per_node 2  run_clm_sft_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --do_eval \
    --seed $RANDOM \
    --fp16 \
    --num_train_epochs 1 \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 6 \
    --evaluation_strategy steps \
    --eval_steps 500 \
    --save_steps 5000 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --modules_to_save ${modules_to_save} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --validation_file ${validation_file} \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False 

```

**Comment by sszyl** [comment]
> > > > mkdir lora_model
> > > > cp pytorch_model.bin lora_model/adapter_model.bin
> > > > cp Chinese-LLaMA-LoRA-7b/adapter_config.json lora_model/
> > > > cp Chinese-LLaMA-LoRA-7b/_token_ lora_model/
> > > 
> > > 
> > > 应该是你这里的tokenizer用错了。你把llama的tokenizer copy到了lora_model（alpaca模型）下。 应该从Chinese-Alpaca-LoRA-7b中拷贝`*token*`到lora_model下。
> > 
> > 
> > 不是啊，你自己用微调生成的lora合并过吗？ 是代码这个地方的问题： if tokenizer.pad_token is None: num_new_tokens = smart_tokenizer_and_embedding_resize( special_tokens_dict=dict(pad_token=DEFAULT_PAD_TOKEN), tokenizer=tokenizer, model=None,) 这里会导致新增一个token，变成49954个，导致在合并的时候会不匹配
> 
> Alpaca的词表数量是49954，比LLaMA多一个，本身是这么设计的，没有问题。

对 llama 微调后的词表会多一个[PAD]，即使把llama的tokenizer copy过去bin里面也有emb在，所以合的时候报了个错

**Comment by liuxiaohao-xn** [comment]
> 请提供以下信息：
> 
> 1. `adapter_model.bin`中的embed_tokens.weight的大小是否为(49954,4096)？
> 2. `/asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/output_dir/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000/lora_model`这个路径，是你训练的Alpaca-LoRA路径吗？里面是否有`tokenizer.model`? 如果用LlamaTokenizer加载这个路径，得到的`len(tokenizer)`是多少？
> 
> ```python
> lora_model_path = "/asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/output_dir/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000/lora_model"
> tokenizer = LlamaTokenizer.from_pretrained(lora_model_path)
> print(len(tokenizer))
> ```



> 请提供以下信息：
> 
> 1. `adapter_model.bin`中的embed_tokens.weight的大小是否为(49954,4096)？
> 2. `/asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/output_dir/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000/lora_model`这个路径，是你训练的Alpaca-LoRA路径吗？里面是否有`tokenizer.model`? 如果用LlamaTokenizer加载这个路径，得到的`len(tokenizer)`是多少？
> 
> ```python
> lora_model_path = "/asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/output_dir/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000/lora_model"
> tokenizer = LlamaTokenizer.from_pretrained(lora_model_path)
> print(len(tokenizer))
> ```
谢谢回复
1. 我不知道如何加载这个单独的lora权重adapter_model.bin，你能提供下思路吗？
2. len(tokenizer)=49953，我刚用你提供的代码跑的。

**Comment by ymcui** [comment]
> 请提供以下信息：
> 
> 1. `adapter_model.bin`中的embed_tokens.weight的大小是否为(49954,4096)？
> 2. `/asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/output_dir/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000/lora_model`这个路径，是你训练的Alpaca-LoRA路径吗？里面是否有`tokenizer.model`? 如果用LlamaTokenizer加载这个路径，得到的`len(tokenizer)`是多少？
> 
> ```python
> lora_model_path = "/asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/output_dir/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000/lora_model"
> tokenizer = LlamaTokenizer.from_pretrained(lora_model_path)
> print(len(tokenizer))
> ```

@liuxiaohao-xn  你看一下上面的这个回复，查看一下模型文件adapter_mode.bin中的词向量大小，以及对应的tokenizer.model的大小是否是49954。

**Comment by airaria** [comment]
@liuxiaohao-xn  你下载一份chinese-alpaca-lora-7b（或者chinese-alpaca-plus-lora-7b也可以），从里面把所有tokenizer相关的文件(`*token*`)拷贝到`/asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/output_dir/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000/lora_model`下

**Comment by airaria** [comment]
@sszyl 所以Alpaca合并时不要用llama tokenizer，用alpaca tokenizer

**Comment by liuxiaohao-xn** [comment]
> @liuxiaohao-xn 你下载一份chinese-alpaca-lora-7b（或者chinese-alpaca-plus-lora-7b也可以），从里面把所有tokenizer相关的文件(`*token*`)拷贝到`/asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/output_dir/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000/lora_model`下

感谢提供解决方法，替换为chinese-alpaca-lora-7b的tokenizer相关文件，成功merge。

**Comment by liuxiaohao-xn** [comment]
> @liuxiaohao-xn 看到词表大小不对，你替换下载下来的alpaca的tokenizer然后试一下合并脚本？

感谢提供解决方法，替换为chinese-alpaca-lora-7b的tokenizer相关文件，成功merge。

**Comment by liuxiaohao-xn** [comment]
> ### 多LoRA权重合并 时报 mismatch错误
> 我参考过 #331 #334 并未找到解决办法，请求解答，万分感谢。
> 
> 下面是我的训练步骤：
> 
> 1. 下载原生的llama-7B权重，用convert_llama_weights_to_hf.py转换成llama-7B-hf权重；
> 2. 下载chinese-llama-plus-lora-7b权重，与llama-7B-hf用 merge_llama_with_chinese_lora.py合并得到chinese-llama-7B-plus-hf权重；
> 3. 然后用run_clm_sft_with_peft.py基于chinese-llama-7B-plus-hf训练得到lora权重adapter_model.bin
> 
> 用下面步骤得到adapter_model.bin，参考#361
> 
> ```shell
> mkdir lora_model
> cp pytorch_model.bin lora_model/adapter_model.bin
> cp Chinese-LLaMA-LoRA-7b/adapter_config.json lora_model/
> cp Chinese-LLaMA-LoRA-7b/*token* lora_model/
> ```
> 
> 4. 然后用merge_llama_with_chinese_lora.py将llama-7B-hf权重， chinese-llama-plus-lora-7b权重， adapter_model.bin权重合并得到最终的chinese-alpaca-7B-Plus权重模型
> 
> **但是执行步骤4时候报错了**
> 
> ### 报错日志
> ```shell
> ===================================BUG REPORT===================================
> Welcome to bitsandbytes. For bug reports, please run
> 
> python -m bitsandbytes
> 
>  and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> ================================================================================
> bin /asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
> /asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: /asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
>   warn(msg)
> /asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: /asr_lu/user/luchuanze/cudnn11/lib: did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
>   warn(msg)
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
> /asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
> Either way, this might cause trouble in the future:
> If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
>   warn(msg)
> CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
> CUDA SETUP: Highest compute capability among GPUs detected: 8.0
> CUDA SETUP: Detected CUDA version 110
> CUDA SETUP: Loading binary /asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda110.so...
> Base model: /asr_lu/user/liuxiaohao/project/LLaMA/llama_hf/7B
> LoRA model(s) ['/asr_lu/user/liuxiaohao/project/LLaMA/Chinese-LLaMA_lora/Chinese-LLaMA-Plus-7B', '/asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/output_dir/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000/lora_model']:
> Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:08<00:00,  4.20s/it]
> Peft version: 0.3.0.dev0
> Loading LoRA for 7B model
> Loading LoRA /asr_lu/user/liuxiaohao/project/LLaMA/Chinese-LLaMA_lora/Chinese-LLaMA-Plus-7B
> Extended vocabulary size to 49953
> Merging with merge_and_unload...
> Loading LoRA /asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/output_dir/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000/lora_model
> Traceback (most recent call last):
>   File "merge_llama_with_chinese_lora.py", line 248, in <module>
>     lora_model = PeftModel.from_pretrained(
>   File "/asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/peft/peft_model.py", line 163, in from_pretrained
>     model = set_peft_model_state_dict(model, adapters_weights)
>   File "/asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/peft/utils/save_and_load.py", line 74, in set_peft_model_state_dict
>     model.load_state_dict(peft_model_state_dict, strict=False)
>   File "/asr_lu/user/liuxiaohao/application/miniconda3/envs/ddp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
>         size mismatch for base_model.model.model.embed_tokens.weight: copying a param with shape torch.Size([49954, 4096]) from checkpoint, the shape in current model is torch.Size([49953, 4096]).
>         size mismatch for base_model.model.lm_head.weight: copying a param with shape torch.Size([49954, 4096]) from checkpoint, the shape in current model is torch.Size([49953, 4096]).
> ```
> 
> ### 报错源码
> ```python
> for lora_index, lora_model_path in enumerate(lora_model_paths):
>         print(f"Loading LoRA {lora_model_path}")
>         tokenizer = LlamaTokenizer.from_pretrained(lora_model_path)
>         if base_model.get_input_embeddings().weight.size(0) != len(tokenizer):
>             base_model.resize_token_embeddings(len(tokenizer))
>             print(f"Extended vocabulary size to {len(tokenizer)}")
> 
>         first_weight = base_model.model.layers[0].self_attn.q_proj.weight
>         first_weight_old = first_weight.clone()
> 
>         if hasattr(peft.LoraModel,'merge_and_unload'):
>             lora_model = PeftModel.from_pretrained(    # 这里报错
>                 base_model,
>                 lora_model_path,
>                 device_map={"": "cpu"},
>                 torch_dtype=torch.float16,
>             )
> ```
> 
> 在合并llama-7B-hf权重与chinese-llama-plus-lora-7b权重并没有报错；此时base_model.get_input_embeddings().weight.size(0) == len(tokenizer)==49953；
> 
> 但在合并adapter_model.bin权重时报size mismatch。
> 
> 下面是我的合并脚本
> 
> ```shell
> # llama_hf + llama_lora + alpaca_lora
> # 7B-Plus
> base_model=/asr_lu/user/liuxiaohao/project/LLaMA/llama_hf/7B
> llama_lora_model=/asr_lu/user/liuxiaohao/project/LLaMA/Chinese-LLaMA_lora/Chinese-LLaMA-Plus-7B
> alpaca_lora_model=/asr_lu/user/liuxiaohao/project/LLM/Chinese-LLaMA-Alpaca/output_dir/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000/lora_model
> output_type=huggingface
> output_dir=/asr_lu/user/liuxiaohao/project/LLaMA/chinese_alpaca_lora_merge_llama_hf/${output_type}/7B-Plus_lora_train_2M_CN_rm_5000/checkpoint-5000
> 
> 
> python merge_llama_with_chinese_lora.py \
>     --base_model ${base_model} \
>     --lora_model ${llama_lora_model},${alpaca_lora_model} \
>     --output_type ${output_type} \
>     --output_dir ${output_dir}
> ```
> 
> ### 必查项目（前三项只保留你要问的）
> * [x]  **基础模型**： Alpaca-Plus
> * [x]  **运行系统**： Linux
> * [x]  **问题分类**： 模型转换和合并
> * [x]  （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
> * [x]  （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案

问题已解决，感谢各位提供的解决思路：

因步骤3训练时，会新增一个token [PAD]，所以在merge alpaca时不能使用llama lora系列模型下的tokenizer相关文件，需要使用alpaca lora系列模型下的的tokenizer相关文件，如
```shell
mkdir lora_model
cp pytorch_model.bin lora_model/adapter_model.bin
cp Chinese_alpaca_plus_lora_7b/adapter_config.json lora_model/
cp Chinese_alpaca_plus_lora_7b/*token* lora_model/
```

这里有个问题，如果官方没有提供alpaca lora系列模型下载路径，那么我们就不能merge得到自己的alpaca ？

**Comment by airaria** [comment]
其实只要在llama tokenizer基础上加一个pad_token作为special token，使其词表长度为49954即可。

**Comment by lovelj** [comment]
> 其实只要在llama tokenizer基础上加一个pad_token作为special token，使其词表长度为49954即可。

我试了这种方式，报了新的错误
Setting ds_accelerator to cuda (auto detect)
Base model: /home/rccv/develop/jie.lian/gitmodel/chinese-alpaca-plus-13b-hf
LoRA model(s) ['model/chinese_llama_plus_lora_13b', 'model/chinese_alpaca_plus_lora_13b']:
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:27<00:00,  9.14s/it]
Peft version: 0.3.0.dev0
Loading LoRA for 13B model
Loading LoRA model/chinese_llama_plus_lora_13b...
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
base_model vocab size: 49954
tokenizer vocab size: 49954
Loading LoRA weights
Traceback (most recent call last):
  File "/home/rccv/develop/jie.lian/Chinese-LLaMA-Alpaca-main/scripts/merge_llama_with_chinese_lora.py", line 281, in <module>
    assert lora_model_sd['base_model.model.model.embed_tokens.weight'].shape[0]==len(tokenizer), \
AssertionError: The vocab size of the tokenizer does not match the vocab size of the LoRA weight.
Did you misuse the LLaMA tokenizer with the Alpaca-LoRA weight?
Make sure that you use LLaMA tokenizer with the LLaMA-LoRA weight and Alpaca tokenizer with the Alpaca-LoRA weight!
